apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project-alpha.name" . }}-config
  labels: {{- include "project-alpha.labels" . | nindent 4 }}
data:
  username: {{ .Values.username }}
  db: {{ .Values.db }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project-alpha.name" . }}-initdb
data:
  initdb.sql: |- {{ .Files.Get "data/initdb.sql" | nindent 4 }}
