apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "project-alpha.name" . }}
  labels: {{- include "project-alpha.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "project-alpha.name" . }}
  replicas: 1
  selector:
    matchLabels: {{- include "project-alpha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "project-alpha.labels" . | nindent 8 }}
      annotations: {{- include "project-alpha.enableLinkerd" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: postgres:11
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: {{ include "project-alpha.name" . }}
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d/initdb.sql
          subPath: initdb.sql
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-alpha.name" . }}-config
                key: db
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-alpha.name" . }}-config
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "project-alpha.name" . }}-secret
                key: password
      volumes:
        - name: initdb
          configMap:
            name: {{ include "project-alpha.name" . }}-initdb
  volumeClaimTemplates:
  - metadata:
      name: {{ include "project-alpha.name" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi
