apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-alpha.name" . }}
  labels: {{- include "project-alpha.labels" . | nindent 4 }}
spec:
  selector: {{- include "project-alpha.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
