apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "project-alpha.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /api/{{- .Chart.Name -}}(/|$)(.*)
            backend:
              serviceName: {{ include "project-alpha.name" . }}
              servicePort: 8080
