apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-alpha.name" . }}-secret
  labels: {{- include "project-alpha.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.password }}
