apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-ui
  labels:
    app: alpha-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-ui
  template:
    metadata:
      labels:
        app: alpha-ui
    spec:
      containers:
        - name: alpha-ui
          image: localhost:32000/alpha-ui:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-ui
spec:
  selector:
    app: alpha-ui
  ports:
    - protocol: TCP
      port: 80
