apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alpha-postgres
spec:
  serviceName: alpha-postgres
  replicas: 1
  selector:
    matchLabels:
      app: alpha-postgres
  template:
    metadata:
      labels:
        app: alpha-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d/initdb.sql
          subPath: initdb.sql
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: alpha-postgres-config
                key: db
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: alpha-postgres-config
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: alpha-postgres-secret
                key: password
      volumes:
        - name: initdb
          configMap:
            name: alpha-postgres-initdb
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: microk8s-hostpath
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-postgres
spec:
  selector:
    app: alpha-postgres
  ports:
    - protocol: TCP
      port: 5432
