apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "project-alpha.name" . }}
  annotations: {{- include "project-alpha.ingressLinkerd" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "project-alpha.name" . }}
              servicePort: 80
